# Generated by Django 3.2.12 on 2022-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('adress', models.CharField(max_length=30, verbose_name='Direccion')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='Telefono')),
                ('phone2', models.CharField(blank=True, max_length=10, null=True, verbose_name='2do telefono')),
            ],
        ),
    ]
