# Generated by Django 3.2.12 on 2022-02-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('section', models.CharField(choices=[('BL', 'BLUSAS'), ('SV', 'SAYAS /VESTIDOS'), ('RI', 'ROPA INTERIOR'), ('PL', 'Pantalones/Licras'), ('CP', 'CAMISAS/ PULOVERES '), ('PH', 'PANTALONES DE HOMBRE'), ('MI', 'MIXTOS')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('ordered', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.service')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateField(auto_now=True)),
                ('ordered', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('extra_price', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('service', models.ManyToManyField(to='clients.OrderService')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
